
version: "3.7"

services:
  db:
    image: "postgres:12"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/installation:/docker-entrypoint-initdb.d
    ports:
      - ${PG_PORT_EXPOSE}:5432
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=${KC_USER}
      - KEYCLOAK_PASSWORD=${KC_PASSWORD}
      - KEYCLOAK_IMPORT=/tmp/realm/import/oli-webservice-realm.json
    ports:
      - ${KC_PORT_EXPOSE}:8080
    depends_on:
      - db
    volumes:
      - ./keycloak:/tmp
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - NODE_ENV=${NODE_ENV}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
    volumes: 
        - ./api/logs:/home/node/app/logs
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
      - keycloak